# Generated by Django 2.0 on 2017-12-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='przykladowa_osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOsoby', models.IntegerField()),
                ('imieOsoby', models.CharField(max_length=240)),
            ],
            options={
                'verbose_name_plural': 'Obywatelki',
            },
        ),
    ]
