# Generated by Django 2.0 on 2018-01-24 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyluna_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop_schedule',
            old_name='time',
            new_name='workshop_time',
        ),
    ]
