# Generated by Django 2.0 on 2017-12-19 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyluna_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Classes_Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('classes_id', models.ForeignKey(on_delete='CASCADE', to='dyluna_app.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Time',
            fields=[
                ('meal_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dyluna_app.Meal')),
                ('meal_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dyluna_app.User')),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dieta_id',
            field=models.ForeignKey(on_delete='CASCADE', to='dyluna_app.Diet'),
        ),
        migrations.AddField(
            model_name='classes_schedule',
            name='place_id',
            field=models.ForeignKey(on_delete='CASCADE', to='dyluna_app.Place'),
        ),
        migrations.AddField(
            model_name='classes',
            name='equipment_id',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='dyluna_app.Equipment'),
        ),
        migrations.AddField(
            model_name='classes',
            name='type_id',
            field=models.ForeignKey(on_delete='CASCADE', to='dyluna_app.Type'),
        ),
        migrations.AddField(
            model_name='classes',
            name='user_id',
            field=models.ForeignKey(on_delete='CASCADE', to='dyluna_app.User'),
        ),
    ]
