# Generated by Django 2.0 on 2017-12-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyluna_app', '0002_auto_20171219_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='user_id',
        ),
        migrations.AddField(
            model_name='classes',
            name='user_preferences_of_classes',
            field=models.ManyToManyField(db_table='user_preferences_of_classes', to='dyluna_app.User'),
        ),
    ]
