# Generated by Django 2.0 on 2017-12-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyluna_app', '0003_auto_20171219_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='equipment_id',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='classes_schedule',
            old_name='classes_id',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='classes_schedule',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='meal_time',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dieta_id',
            new_name='dieta',
        ),
        migrations.RenameField(
            model_name='user_role',
            old_name='user_id',
            new_name='user',
        ),
    ]
