# Generated by Django 2.0 on 2017-12-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyluna_app', '0004_auto_20171219_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='classes',
            name='user_preferences_of_classes',
        ),
        migrations.AddField(
            model_name='classes',
            name='user',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='dyluna_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferences',
            name='classes',
            field=models.ForeignKey(on_delete='CASCADE', to='dyluna_app.Classes'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to='dyluna_app.User'),
        ),
    ]
