# Generated by Django 2.0 on 2017-12-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyluna_app', '0005_auto_20171220_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop_Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete='CASCADE', to='dyluna_app.Place')),
            ],
        ),
        migrations.RemoveField(
            model_name='classes_schedule',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='classes_schedule',
            name='place',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='classes',
            new_name='workshop',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dieta',
            new_name='diet',
        ),
        migrations.RenameModel(
            old_name='Classes',
            new_name='Workshop',
        ),
        migrations.DeleteModel(
            name='Classes_Schedule',
        ),
        migrations.AddField(
            model_name='workshop_schedule',
            name='workshop',
            field=models.ForeignKey(on_delete='CASCADE', to='dyluna_app.Workshop'),
        ),
    ]
